package com.example.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val appName: String,
    val welcomeUser: (String) -> String,
    val searchPlaceholder: String,
    val quickAdd: String,
    val aiAssistantTitle: String,
    val aiAssistantSubtitle: String,
    val recentActivities: String,
    val noResultsFor: (String) -> String,
    
    // Modules
    val modulePhotos: String,
    val moduleBookmarks: String,
    val moduleNotes: String,
    val moduleSubscriptions: String,
    val moduleSocialMedia: String,
    val moduleBank: String,
    val moduleDonations: String,
    val moduleAiTools: String,
    val modulePasswords: String,
    val moduleTasks: String,
    val moduleAdmin: String,
    
    // Common Buttons & Dialogs
    val cancel: String,
    val save: String,
    val confirm: String,
    val delete: String,
    val edit: String,
    val add: String,
    val back: String,
    val close: String,
    val show: String,
    val hide: String,
    val active: String,
    val cancelled: String,
    val pending: String,
    val completed: String,
    val all: String,
    
    // Bottom Bar
    val navDashboard: String,
    val navPhotos: String,
    val navTasks: String,
    val navSubscriptions: String,
    val navBank: String,
    val navMore: String,
    
    // Auth Screen
    val signIn: String,
    val signInSubtitle: String,
    val email: String,
    val password: String,
    val googleSignIn: String,
    val biometricSignIn: String,
    val forgotPassword: String,
    val dontHaveAccount: String,
    
    // Quick Add Sheet
    val addFavoriteBookmark: String,
    val addNoteOrIdea: String,
    val addNewSubscription: String,
    val addSocialAccount: String,
    val addBankAccount: String,
    val addNewDonation: String,

    // Screen specific titles & labels
    val photosTitle: String,
    val bookmarksTitle: String,
    val notesTitle: String,
    val subscriptionsTitle: String,
    val socialTitle: String,
    val bankTitle: String,
    val donationsTitle: String,
    val aiToolsTitle: String,
    val passwordsTitle: String,
    val tasksTitle: String,
    val adminTitle: String,
    val aiChatTitle: String,
    val aiChatPlaceholder: String,
    
    // Additional labels
    val highPriority: String,
    val mediumPriority: String,
    val lowPriority: String,
    val dueDate: String,
    val category: String,
    val titleLabel: String,
    val contentLabel: String,
    val tagsLabel: String,
    val urlLabel: String,
    val usernameLabel: String,
    val platformLabel: String,
    val followersLabel: String,
    val bankNameLabel: String,
    val ibanLabel: String,
    val accountHolderLabel: String,
    val amountLabel: String,
    val organizationLabel: String,
    val descriptionLabel: String,
    val serviceNameLabel: String,
    val monthlyCostLabel: String,
    val renewalDateLabel: String,
    val albumLabel: String,
    val moveToTrash: String,
    val trashBin: String,
    val systemStatus: String,
    val usersCount: String,
    val activityLogs: String,
    val switchRole: String,
    val mainUser: String,
    val systemAdmin: String
)

val ArabicStrings = AppStrings(
    appName = "رتب حالك",
    welcomeUser = { name -> "مرحباً $name" },
    searchPlaceholder = "ابحث في البيانات والأقسام...",
    quickAdd = "إضافة سريعة",
    aiAssistantTitle = "المساعد الذكي Gemini AI",
    aiAssistantSubtitle = "أسأل الذكاء الاصطناعي عن مهامك، صورك، واشتراكاتك",
    recentActivities = "آخر الأنشطة والأنظمة",
    noResultsFor = { query -> "لا توجد نتائج مطابقة لـ \"$query\"" },
    
    modulePhotos = "الصور الخاصة",
    moduleBookmarks = "المواقع المفضلة",
    moduleNotes = "الأفكار والملاحظات",
    moduleSubscriptions = "الاشتراكات",
    moduleSocialMedia = "مواقع التواصل",
    moduleBank = "الحسابات البنكية",
    moduleDonations = "التبرعات",
    moduleAiTools = "أدوات AI",
    modulePasswords = "كلمات المرور",
    moduleTasks = "المهام والتقويم",
    moduleAdmin = "لوحة التحكم",
    
    cancel = "إلغاء",
    save = "حفظ",
    confirm = "تأكيد",
    delete = "حذف",
    edit = "تعديل",
    add = "إضافة",
    back = "رجوع",
    close = "إغلاق",
    show = "إظهار",
    hide = "إخفاء",
    active = "نشط",
    cancelled = "ملغى",
    pending = "قيد التنفيذ",
    completed = "مكتملة",
    all = "الكل",
    
    navDashboard = "الرئيسية",
    navPhotos = "الصور",
    navTasks = "المهام",
    navSubscriptions = "الاشتراكات",
    navBank = "الحسابات",
    navMore = "المزيد",
    
    signIn = "تسجيل الدخول",
    signInSubtitle = "مرحباً بك مجدداً في تطبيق 'رتب حالك'",
    email = "البريد الإلكتروني",
    password = "كلمة المرور",
    googleSignIn = "متابعة بواسطة Google",
    biometricSignIn = "الدخول بالبصمة الحيوية",
    forgotPassword = "نسيت كلمة المرور؟",
    dontHaveAccount = "ليس لديك حساب؟ إنشاء حساب جديد",
    
    addFavoriteBookmark = "موقع مفضل",
    addNoteOrIdea = "ملاحظة أو فكرة",
    addNewSubscription = "اشتراك جديد",
    addSocialAccount = "حساب تواصل اجتماعي",
    addBankAccount = "حساب بنكي آمن",
    addNewDonation = "تبرع جديد",

    photosTitle = "معرض الصور الخاص والمحمي",
    bookmarksTitle = "المواقع والروابط المفضلة",
    notesTitle = "الأفكار والملاحظات الذكية",
    subscriptionsTitle = "الاشتراكات الشهرية والسنوية",
    socialTitle = "مواقع وحسابات التواصل الاجتماعي",
    bankTitle = "الحسابات البنكية والمحافظ",
    donationsTitle = "سجل التبرعات والأعمال الخيرية",
    aiToolsTitle = "دليل أدوات الذكاء الاصطناعي",
    passwordsTitle = "خزينة كلمات المرور المشفرة",
    tasksTitle = "إدارة المهام والتقويم",
    adminTitle = "لوحة تحكم مدير النظام",
    aiChatTitle = "المساعد الذكي لتطبيق 'رتب حالك'",
    aiChatPlaceholder = "اكتب سؤالك أو طلبك هنا...",
    
    highPriority = "عالية",
    mediumPriority = "متوسطة",
    lowPriority = "منخفضة",
    dueDate = "تاريخ الاستحقاق",
    category = "التصنيف",
    titleLabel = "العنوان",
    contentLabel = "المحتوى",
    tagsLabel = "الوسوم",
    urlLabel = "الرابط / URL",
    usernameLabel = "اسم المستخدم / الإيميل",
    platformLabel = "المنصة",
    followersLabel = "المتابعين / المشتركين",
    bankNameLabel = "اسم البنك",
    ibanLabel = "رقم الأيبان (IBAN)",
    accountHolderLabel = "اسم صاحب الحساب",
    amountLabel = "المبلغ",
    organizationLabel = "الجهة / الجمعية",
    descriptionLabel = "الوصف",
    serviceNameLabel = "اسم الخدمة",
    monthlyCostLabel = "التكلفة الشهرية",
    renewalDateLabel = "تاريخ التجديد",
    albumLabel = "الألبوم",
    moveToTrash = "نقل لسلة المحذوفات",
    trashBin = "سلة المحذوفات",
    systemStatus = "حالة النظام",
    usersCount = "المستخدمين",
    activityLogs = "سجلات العمليات",
    switchRole = "تبديل الصلاحية",
    mainUser = "مستخدم رئيسي",
    systemAdmin = "مسؤول النظام (Admin)"
)

val EnglishStrings = AppStrings(
    appName = "Ratib Halak",
    welcomeUser = { name -> "Welcome $name" },
    searchPlaceholder = "Search data and categories...",
    quickAdd = "Quick Add",
    aiAssistantTitle = "Gemini AI Assistant",
    aiAssistantSubtitle = "Ask AI about your tasks, photos, and subscriptions",
    recentActivities = "Recent Activities & System Logs",
    noResultsFor = { query -> "No matching results for \"$query\"" },
    
    modulePhotos = "Private Photos",
    moduleBookmarks = "Bookmarks",
    moduleNotes = "Notes & Ideas",
    moduleSubscriptions = "Subscriptions",
    moduleSocialMedia = "Social Media",
    moduleBank = "Bank Accounts",
    moduleDonations = "Donations",
    moduleAiTools = "AI Tools",
    modulePasswords = "Password Vault",
    moduleTasks = "Tasks & Calendar",
    moduleAdmin = "Admin Panel",
    
    cancel = "Cancel",
    save = "Save",
    confirm = "Confirm",
    delete = "Delete",
    edit = "Edit",
    add = "Add",
    back = "Back",
    close = "Close",
    show = "Show",
    hide = "Hide",
    active = "Active",
    cancelled = "Cancelled",
    pending = "Pending",
    completed = "Completed",
    all = "All",
    
    navDashboard = "Home",
    navPhotos = "Photos",
    navTasks = "Tasks",
    navSubscriptions = "Subscriptions",
    navBank = "Bank",
    navMore = "More",
    
    signIn = "Sign In",
    signInSubtitle = "Welcome back to Ratib Halak",
    email = "Email Address",
    password = "Password",
    googleSignIn = "Continue with Google",
    biometricSignIn = "Biometric Login",
    forgotPassword = "Forgot Password?",
    dontHaveAccount = "Don't have an account? Sign Up",
    
    addFavoriteBookmark = "Favorite Bookmark",
    addNoteOrIdea = "Note or Idea",
    addNewSubscription = "New Subscription",
    addSocialAccount = "Social Media Account",
    addBankAccount = "Secure Bank Account",
    addNewDonation = "New Donation",

    photosTitle = "Private Photo Vault",
    bookmarksTitle = "Bookmarks & Links",
    notesTitle = "Notes & Smart Ideas",
    subscriptionsTitle = "Subscriptions Tracker",
    socialTitle = "Social Media Accounts",
    bankTitle = "Bank Accounts & Wallets",
    donationsTitle = "Donations & Charity Log",
    aiToolsTitle = "AI Tools Directory",
    passwordsTitle = "Encrypted Password Vault",
    tasksTitle = "Tasks & Calendar",
    adminTitle = "Admin Dashboard",
    aiChatTitle = "Ratib Halak AI Assistant",
    aiChatPlaceholder = "Type your question or request here...",
    
    highPriority = "High",
    mediumPriority = "Medium",
    lowPriority = "Low",
    dueDate = "Due Date",
    category = "Category",
    titleLabel = "Title",
    contentLabel = "Content",
    tagsLabel = "Tags",
    urlLabel = "URL / Link",
    usernameLabel = "Username / Email",
    platformLabel = "Platform",
    followersLabel = "Followers / Subscribers",
    bankNameLabel = "Bank Name",
    ibanLabel = "IBAN Number",
    accountHolderLabel = "Account Holder",
    amountLabel = "Amount",
    organizationLabel = "Organization / Charity",
    descriptionLabel = "Description",
    serviceNameLabel = "Service Name",
    monthlyCostLabel = "Monthly Cost",
    renewalDateLabel = "Renewal Date",
    albumLabel = "Album",
    moveToTrash = "Move to Trash",
    trashBin = "Trash Bin",
    systemStatus = "System Status",
    usersCount = "Users",
    activityLogs = "Activity Logs",
    switchRole = "Switch Role",
    mainUser = "Main User",
    systemAdmin = "System Admin"
)

val LocalAppStrings = staticCompositionLocalOf { ArabicStrings }

val AppLanguage: AppStrings
    @Composable
    @ReadOnlyComposable
    get() = LocalAppStrings.current
